/**
 * UTS Phase 1 — Universal Training Scheduler Types
 *
 * Authoritative naming conventions (from audit):
 *  - Recovery exercises: exerciseRole === 'cooldown'  (NOT 'mobility'/'recovery'/'stretching')
 *  - Maintenance ring:  exerciseRole === 'cooldown'   (the purple ring in ConcentricRings)
 *  - Week standard:     Sunday = 0 = 'א' (matches all Hebrew day arrays in the codebase)
 */

// ── Hebrew Day ─────────────────────────────────────────────────────────────
// Index 0='א'(Sun) … 6='ש'(Sat) — matches JS Date.getDay() directly.
export type HebrewDayLetter = 'א' | 'ב' | 'ג' | 'ד' | 'ה' | 'ו' | 'ש';

// ── Recurring Template ─────────────────────────────────────────────────────
// Stored in users/{uid}.lifestyle.recurringTemplate
// Keys   = Hebrew day letters
// Values = array of Firestore program document IDs for that day
//
// Example: { 'א': ['H2279XsRGDg9G370J7S9'], 'ג': ['pull_id', 'core_id'] }
// Rest days are expressed by OMITTING the day from the template, or by
// setting type: 'rest' on the concrete UserScheduleEntry.
export type RecurringTemplate = Partial<Record<HebrewDayLetter, string[]>>;

// ── Schedule Entry Types ───────────────────────────────────────────────────
// 'training'   → standard strength/run/hybrid workout
// 'rest'       → active recovery (exerciseRole:'cooldown', difficulty:1)
// 'assessment' → reserved for future visual-assessment days
export type ScheduleEntryType = 'training' | 'rest' | 'assessment';

// 'recurring'      → hydrated from recurringTemplate (auto-generated)
// 'manual'         → user explicitly placed/moved this workout
// 'auto'           → system placed this (e.g., first-workout flow)
// 'google_calendar'→ synced from external calendar (Phase 4)
// 'community'      → auto-populated from a joined community group's scheduleSlots
export type ScheduleEntrySource =
  | 'recurring'
  | 'manual'
  | 'auto'
  | 'google_calendar'
  | 'community';

// ── Activity category (mirrors activity.types but avoids circular import) ──
export type ScheduleActivityCategory = 'strength' | 'cardio' | 'maintenance' | 'walking';

// ── Firestore Document: userSchedule/{userId}_{dateISO} ───────────────────
//
// Documents are stored as `UserScheduleDay` (the wrapper below) — the
// individual `UserScheduleEntry` objects live inside its `entries[]` array.
//
// Persisted entries always carry an `entryId` (generated by `addScheduleEntry`
// when callers don't supply one). The field is left optional only because
// callers occasionally synthesize transient in-memory entries — for example
// the `scheduleDays`-driven recurring fallback in AgendaDayCard.tsx — that
// are never round-tripped through Firestore. The drag layer treats those
// `entryId === undefined` entries as "synthesized recurring" and rebuilds
// them from the recurring template if moved.
export interface UserScheduleEntry {
  /** Stable id within its day. Always set on persisted entries. */
  entryId?: string;
  userId: string;
  date: string;               // 'YYYY-MM-DD'
  programIds: string[];       // Firestore program doc IDs; empty for rest days
  type: ScheduleEntryType;
  source: ScheduleEntrySource;
  completed: boolean;
  completedWorkoutId?: string; // set when the workout session is finished
  /** Which ring categories are scheduled for this day (e.g. ['strength','cardio']) */
  scheduledCategories?: ScheduleActivityCategory[];
  /** Time-based scheduling — 'HH:MM' (24h) within the day */
  startTime?: string;
  /** Reserved for Google Calendar Phase 4 */
  externalId?: string;
  /** Community group reference — only present when source === 'community'. */
  groupId?: string;
  /** Denormalised community group display name — only when source === 'community'. */
  groupName?: string;
  /**
   * Tombstone flag written by `removeScheduleEntry` when the last entry on a
   * recurring-template day is deleted.  When `true`, `hydrateFromTemplate`
   * skips the date so the deletion persists instead of being re-populated.
   */
  override?: boolean;
  createdAt?: any;             // Firebase serverTimestamp()
  updatedAt?: any;
}

// ── Day wrapper: userSchedule/{userId}_{dateISO} ─────────────────────────
/**
 * Authoritative Firestore document shape:
 *   userSchedule/{uid}_{date} → { userId, date, entries: UserScheduleEntry[], updatedAt }
 *
 * One day = one document = many entries. Multiple workouts on the same date
 * (personal + community, or two strength sessions) coexist as separate
 * elements of the `entries` array.
 */
export interface UserScheduleDay {
  userId: string;
  date: string;
  entries: UserScheduleEntry[];
  updatedAt: any;
}
