// AUTO-GENERATED by scripts/gen-equipment-icon-manifest.mjs — DO NOT EDIT.
// Build-time list of the equipment SVG assets in public/assets/icons/equipment/.
// Refreshed by the predev/prebuild npm hooks. Consulted synchronously so an
// authored iconKey can win over the static canonical collapse without any
// runtime fs / fetch (no broken-image flicker). Includes files that are absent
// from ICON_KEY_TO_SVG (e.g. training_steps.svg), which is the whole point.
export const EQUIPMENT_ICON_FILES: ReadonlySet<string> = new Set([
  'Abdominal_wheel.svg',
  'Climbing rope.svg',
  'Rings.svg',
  'back_pack.svg',
  'chair.svg',
  'kettlebell.svg',
  'long_resistance_band.svg',
  'mat.svg',
  'pants.svg',
  'parallel_bars.svg',
  'parallel_bars_home.svg',
  'pullup_bar_door.svg',
  'pullupbar_park.svg',
  'ring_park.svg',
  'skipping_rope.svg',
  'sofa.svg',
  'steps.svg',
  'stool.svg',
  'street_bench.svg',
  'table.svg',
  'training_steps.svg',
  'trx.svg',
  'weight_belt.svg',
  'yoga_block.svg',
]);
